- name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.27.151.73
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd cleancity
            git pull origin main
            npm install
            # Jika proses ada, restart. Jika tidak ada, jalankan aplikasi.
            /usr/local/bin/pm2 delete cleancity || true
            /usr/local/bin/pm2 start app.js --name "cleancity"
            /usr/local/bin/pm2 save